# Generated by Django 2.2.7 on 2019-11-10 02:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feria_ing', '0001_initial'),
        ('users', '0002_profesor_profe'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Profesor')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feria_ing.Project')),
            ],
        ),
    ]
