# Generated by Django 2.2.7 on 2019-11-11 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feria_ing', '0001_initial'),
        ('users', '0003_evaluacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evaluacion',
            name='profesor',
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='profesor',
            field=models.ManyToManyField(to='users.Profesor'),
        ),
        migrations.RemoveField(
            model_name='evaluacion',
            name='proyecto',
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='proyecto',
            field=models.ManyToManyField(to='feria_ing.Project'),
        ),
    ]
