# Generated by Django 2.2.7 on 2019-11-11 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feria_ing', '0001_initial'),
        ('users', '0006_auto_20191111_1421'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evaluacion',
            name='profesor',
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='profesor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.Profesor'),
        ),
        migrations.RemoveField(
            model_name='evaluacion',
            name='proyecto',
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='proyecto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='feria_ing.Project'),
        ),
    ]
