# Generated by Django 2.2.7 on 2019-11-11 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20191111_1437'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evaluacion',
            name='profesor',
        ),
        migrations.RemoveField(
            model_name='evaluacion',
            name='proyecto',
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='profesor_id',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='proyecto_id',
            field=models.IntegerField(default=None),
        ),
    ]
