# Generated by Django 2.2.7 on 2019-11-14 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20191111_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluacion',
            name='calificacion',
            field=models.IntegerField(default=None),
        ),
    ]
