# Generated by Django 2.1 on 2019-11-20 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_evaluacion_calificacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='matricula',
            field=models.CharField(max_length=25, primary_key=True, serialize=False),
        ),
    ]
