# Generated by Django 2.1 on 2019-11-20 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20191120_0557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profesor',
            name='matricula',
            field=models.CharField(max_length=25, primary_key=True, serialize=False),
        ),
    ]
