# Generated by Django 2.1 on 2019-11-05 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=140)),
                ('descripcion', models.TextField()),
                ('categoria', models.CharField(max_length=140)),
                ('requierements', models.CharField(max_length=140)),
                ('evaluaciones', models.IntegerField()),
            ],
        ),
    ]
