# Generated by Django 2.2.7 on 2019-11-06 02:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('abreviacion', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('num_proyectos', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=140)),
                ('descripcion', models.TextField()),
                ('requierements', models.CharField(max_length=140)),
                ('evaluaciones', models.IntegerField()),
                ('categoria', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='feria_ing.Categoria')),
            ],
        ),
    ]
