# Generated by Django 2.1 on 2019-11-20 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feria_ing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='requierements',
            field=models.CharField(max_length=140, verbose_name='Requerimientos'),
        ),
    ]
